apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: prod-nginx-service
  namespace: prod-meridian
spec:
  ports:
  - nodePort: 31003
    port: 8086
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: prod-nginx-deployment
  namespace: prod-meridian
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-nginx-ingress
  namespace: prod-meridian
spec:
  ingressClassName: nginx
  rules:
  - host: prod.example.com
    http:
      paths:
      - backend:
          service:
            name: prod-nginx-service
            port:
              number: 8086
        path: /
        pathType: Prefix
