apiVersion: v1
kind: Service
metadata:
  name: kongpostgres
  labels:
    app: postgres  
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 #Cluster IP Level
      targetPort: 5432
      nodePort: 30538  #External Port

  