apiVersion: v2 #Helm API Version
name: kong-postgres-chart
description: A helm chart for Postgres - Kong
keywords:
  - "postgres"
type: application
appVersion: 1.0.0 # Version of the Application
version: 1.0.0 # Version of the chart
