apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: prod-meridian

bases:
- ../../base

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-deployment
  path: patch-deploy.yaml

patchesStrategicMerge:
- nginx-service.yaml

resources:
  - ingress.yaml